/*
 * VCRConnectionPanel.java
 *
 * Created on March 13, 2007, 3:39 PM
 */

package org.mbari.vcr.qt;

import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import org.mbari.vcr.IVCR;
import org.mbari.vcr.VCRAdapter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import quicktime.std.movies.Movie;

/**
 *
 * @author  brian
 */
public class VCRConnectionPanel extends org.mbari.vcr.ui.VCRConnectionPanel {
    
    private static final Logger log = LoggerFactory.getLogger(VCRConnectionPanel.class);
    
    /** Creates new form VCRConnectionPanel */
    public VCRConnectionPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        urlField = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        timeSourceComboBox = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(300, 200));

        lbl.setText("Movie URL:");

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPane.setViewportView(urlField);

        lbl2.setText("Time source:");

        timeSourceComboBox.setModel(new DefaultComboBoxModel(TimeSource.values()));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbl2)
                    .add(lbl))
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(timeSourceComboBox, 0, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbl)
                    .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl2)
                    .add(timeSourceComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public IVCR getVcr() {
        IVCR vcr = new VCRAdapter();
        try     {
            Movie movie = org.mbari.qt.QT.openMovieFromUrl(new URL(urlField.getText()));
            vcr = new VCR(movie, (TimeSource) timeSourceComboBox.getSelectedItem());
            return vcr;
        }
        catch (Exception e) {
            log.error("Unable to open movie at '" + urlField.getText() + "'", e);
        }

        return vcr;
    }

    public String getVcrPanelName() {
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl2;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JComboBox timeSourceComboBox;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
    
}
